### ISSUE TITLE
Create User/Admin Login

### ISSUE THREAD

**Issue by draymond63** [uwblueprint/rowan-house#2]
## Summary
- One of the biggest pain points of the RISE platform is a clunky sign up flow --> it leads to significant dropoff of interested learners
- Existing auth flow also takes a lot of time for the RHS staff to work with
- We want a comprehensive solution that meets the auth requirements of RHS

#### `Overarching Goal: As a Rowan House Admin/User I need to have a straightforward and simple sign up and login flow` 
- [ ] As an RHS admin I should be able to log in with my email and be recognized as a platform admin
-  [ ] As an RHS learner I should be able to sign up for the platform, providing some information about myself (name, email, town)
-  [ ] As an RHS learner, I should be able to use my sign in details to log back into the platform after some inactivity time
- [ ] As an RHS admin or learner I should be able to log out of my account if desired
- [ ] As an RHS admin or learner I should be automatically logged out of my account after some time (ask Daniel or Dinu about this)
- [ ] *Scoping Needed* As an RHS admin or learner I should be able to sign on with magic links or SSO providers

## Solution (Core Elements) 
- Login page
![image](https://user-images.githubusercontent.com/50289930/151893833-ec414f93-08c1-4ab3-98d9-1282e2959484.png)
![image](https://user-images.githubusercontent.com/50289930/151893872-832f35a9-2aa0-4e20-9cb1-1bae15ad10ce.png)
- Forgot your password page (could potentially be removed if using magic links) 
![image](https://user-images.githubusercontent.com/50289930/151893911-283eb6be-8300-4c18-b200-ae3cea9408b5.png)
- Sign up page
![image](https://user-images.githubusercontent.com/50289930/151893955-52151e85-d765-4fd7-8f39-9f1f7ffe7aac.png)

## Dependencies
- Backend work on auth should be done

## No-Gos 
- TBD: whether we need SSO options or not
